### ISSUE TITLE
LayoutLM from scratch模型是指不经过任何预训练，直接使用docbank训练吗？

### ISSUE THREAD

**Issue by mfxss** [doc-analysis/DocBank#11]
您好，论文表格中，LayoutLM from scratch的效果还不错，比bert初始化参数的效果要好，那么这里模型是指不经过任何预训练，直接使用docbank训练吗？
我下载了docbank，发现标签中没有标注BIE，请问您在训练的时候是否有标注BIE呢？
数据中没有标明图片的大小，而layoutlm中图片是经过resize的，我们这篇有经过缩放吗？图片的大小也是固定的754,1000吗？

**Comment by liminghao1630** [comment]
我们似乎没有提到LayoutLM from scratch，您是在哪里看到的？
我们直接使用语义结构的名称作为token的label，并没有使用BIE标注格式。
DocBank的数据中的bbox的长和宽都是放缩到了0-1000。

**Comment by GZDXLQH** [comment]
您好，LayoutLM from scratch应该是在论文‘DocBank: A Benchmark Dataset for Document Layout Analysis’的5.3result部分提到了，而且效果整体较pre-trained BRET效果较好。
![image](https://user-images.githubusercontent.com/46209516/94151439-fff07480-feac-11ea-99d5-d6d15212cf30.png)

**Comment by liminghao1630** [comment]
是的，没有使用预训练的参数

**Comment by liminghao1630** [comment]
The new version of our paper is under review and the version on arXiv is outdated.
