### ISSUE TITLE
Incorrect of annotation

### ISSUE THREAD

**Issue by tengerye** [doc-analysis/DocBank#12]
I found the coordinates in the annotation file are incorrect. 
For example, `2.tar_1801.00617.gz_idempotents_arxiv_4.txt` in the `DocBank_samples`. The size of image is 1654x2339. However, all bounding boxes do not even reach the half of the page.

The final effect is:
![image](https://user-images.githubusercontent.com/15181821/93019271-7fa65580-f608-11ea-825b-ca6037430dd2.png)

Do I miss anything? @liminghao1630 @wolfshow @ranpox @doc-analysis

**Comment by tengerye** [comment]
Got it. They are normalized coordinates. We need to adjust them. It is quite strange why not use the original coordinates in annotation files.

**Comment by liminghao1630** [comment]
Hi, @tengerye 
In this work, we normalize all the bounding boxes using the size of the PDF pages and scale each value into a range of 0 - 1000 to fit various layouts of documents.
