### ISSUE TITLE
请问预训练模型只支持13个类别的标签种类吗？

### ISSUE THREAD

**Issue by mishidemudong** [doc-analysis/DocBank#13]
请问预训练模型只支持13个类别的标签种类吗？尝试过修改config文件的label2id，labels.txt，增加了两个类别，但报错15和13不匹配。

**Comment by liminghao1630** [comment]
可以设置不载入预训练模型最后的分类器参数，随机初始化你的分类器参数

**Comment by mishidemudong** [comment]
> 可以设置不载入预训练模型最后的分类器参数，随机初始化你的分类器参数

好的，感谢解答
