### ISSUE TITLE
Image resize size?

### ISSUE THREAD

**Issue by alohays** [doc-analysis/DocBank#19]
![image](https://user-images.githubusercontent.com/16367056/97391751-478e7400-1923-11eb-888a-166f49cf7d74.png)

The annotation bbox information and image size do not match.

**Comment by liminghao1630** [comment]
In this work, we normalize all the bounding boxes using the size of the PDF pages and scale each value into a range of 0 - 1000 to fit various layouts of documents.

**Comment by duany049** [comment]
> 
我不知道PDF尺寸的话，怎么把框转换成适应图片的尺寸呢？？
