### ISSUE TITLE
数据集的标注

### ISSUE THREAD

**Issue by tnkong** [doc-analysis/DocBank#2]
您好, 感谢您富有创意的工作,。
这个数据集是根据文字的token标注的, 我看到一个bounding box区域就是一个单词, 这种标注是非常细粒度的。
我在做文档重建方面的研究工作, 请问是否可提供栏目块样式的标注, 即一个bounding box 是正文的一个段落或者标题,次级标题这种类似的标注

**Comment by liminghao1630** [comment]
> 您好, 感谢您富有创意的工作,。
> 这个数据集是根据文字的token标注的, 我看到一个bounding box区域就是一个单词, 这种标注是非常细粒度的。
> 我在做文档重建方面的研究工作, 请问是否可提供栏目块样式的标注, 即一个bounding box 是正文的一个段落或者标题,次级标题这种类似的标注

您好，目前暂时没有这种层次的标注。

**Comment by mdv3101** [comment]
Hi @tnkong,
Did you able to process the dataset with a full bounding box for the text, instead of a single word?

**Comment by xiaoguaishoubaobao** [comment]
> Hi @tnkong,
> Did you able to process the dataset with a full bounding box for the text, instead of a single word?

同样的需要这种数据
