### ISSUE TITLE
Are component-level annotations available?

### ISSUE THREAD

**Issue by martinarroyo** [doc-analysis/DocBank#20]
I was wondering if the annotations for an element (a region comprising one or more tokens), such as for example a paragraph (similar to the annotations for PubLayNet) are available, or if there exists a mechanism to compute them. I suppose running some sort of clustering algorithm could do the work decently, but I would like to know if these annotations already exist.

Thanks in advance for your help!

**Comment by liminghao1630** [comment]
Yes, we convert DocBank to the format of the object detection models and evaluate Faster R-CNN on the test set. The newest result has been updated in GitHub.
The converting process will be given on the newest paper and we will also provide a converting script. Both of them will come soon.

**Comment by doc-analysis** [comment]
[https://github.com/doc-analysis/DocBankLoader](https://github.com/doc-analysis/DocBankLoader)

**Comment by martinarroyo** [comment]
Thanks for the pointers!
