### ISSUE TITLE
Same type different area in one doc

### ISSUE THREAD

**Issue by Damcy** [doc-analysis/DocBank#24]
Thanks for your excellent work!
It looks like that there are no signs used to distinguish regions in the data. For example, there are two paragraphs separated by a title. How can I distinguish these two paragraphs? Tokens in these two paragraphs are all marked as "paragraph" without id or other signs.
Can you release some flags to distinguish regions?

**Comment by liminghao1630** [comment]
For now, we have only the annotation without id for all the same semantic structures on the same page.

**Comment by Damcy** [comment]
Downstream tasks after the layout analysis process are usually sensitive to their regions, for example, paragraph analysis, the relation between title and paragraph, and so on. Maybe DocBank can push a little more?

**Comment by liminghao1630** [comment]
@Damcy 
Sorry, we currently have no relevant plans.

**Comment by Damcy** [comment]
Okay, thanks for your excellent work.

**Comment by xiaoguaishoubaobao** [comment]
> @Damcy
> Sorry, we currently have no relevant plans.

现在支持这个了吗
