### ISSUE TITLE
pdf_process.py script does not generate RGB Values and Label in .txt files

### ISSUE THREAD

**Issue by Apurv3377** [doc-analysis/DocBank#28]
I am trying to use the pdf_process.py script to parse the content from a PDF file and create a annotated file with 10 fields. 
Unfortunately, for both black and colored PDF files I am not getting RGB and Label values.  

Can you please suggest how can I generate a .txt file with 10 fields using this script? 

```
Complex	80	66	198	91	AAEWKY+NimbusRomNo9L-Regu
Block	210	66	288	91	AAEWKY+NimbusRomNo9L-Regu
Floating-Point	299	66	487	91	AAEWKY+NimbusRomNo9L-Regu
```

```
MNRAS	70	94	123	104	UFZJOE+CMR8
000,	128	94	156	104	ECMFEV+CMBX8
1–16	161	94	190	104	UFZJOE+CMR8
(2017)	194	94	234	104	UFZJOE+CMR8
```
Thanks.

**Comment by Root970103** [comment]
> I am trying to use the pdf_process.py script to parse the content from a PDF file and create a annotated file with 10 fields.
> Unfortunately, for both black and colored PDF files I am not getting RGB and Label values.
> 
> Can you please suggest how can I generate a .txt file with 10 fields using this script?
> 
> ```
> Complex	80	66	198	91	AAEWKY+NimbusRomNo9L-Regu
> Block	210	66	288	91	AAEWKY+NimbusRomNo9L-Regu
> Floating-Point	299	66	487	91	AAEWKY+NimbusRomNo9L-Regu
> ```
> 
> ```
> MNRAS	70	94	123	104	UFZJOE+CMR8
> 000,	128	94	156	104	ECMFEV+CMBX8
> 1–16	161	94	190	104	UFZJOE+CMR8
> (2017)	194	94	234	104	UFZJOE+CMR8
> ```
> 
> Thanks.

Hi~ Have you solved this problem? I met the same problem as you. And I haven't figure out what to do.

**Comment by liminghao1630** [comment]
@Apurv3377 @Root970103 
By default, the script will not output the color of the tokens, because the color may be not accurate by our script.  You can manually output it by modifying our script.
As for the label, you can never detect it from an original PDF unless you annotated the semantic structures in some way, like the method in our paper.

**Comment by Apurv3377** [comment]
@Root970103 I have manged to extract the color information using below snippet of code. Nevertheless, as @liminghao1630 suggests detection strictly requires color annotations mentioned in the paper.

```
# 0 for black color.
# RGB values for annotated fields.
wordcolor=obj.graphicstate.ncolor
            if isinstance(wordcolor,int) and wordcolor==0:
               rgb=(0,0,0)
            elif isinstance(wordcolor,tuple) and len(wordcolor) == 3:
             rgb = (
                    int(wordcolor[0]*255),
                    int(wordcolor[1] * 255),
                    int(wordcolor[2] * 255)
                )
```
