### ISSUE TITLE
Possible damaged image files in the dataset

### ISSUE THREAD

**Issue by tankgit** [doc-analysis/DocBank#30]
I have found some broken images from "DocBank_500K_ori_img" which would cause the error while training, considering the great amount of the dataset, the mid-break during training is unbearable.

I suggest the author to re-check the image dataset especially for the following images:
_**9.tar_1501.04477.gz_RobustSwitching-ergodic_3_ori.jpg**_
**_97.tar_1705.02752.gz_kcenters_22_ori.jpg_**
**_66.tar_1504.08256.gz_Manipulation_Partial_Info_without_cref_5_ori.jpg_**
**_88.tar_1704.08423.gz_SingularSystem_1-2_17_ori.jpg_**

None of them could be loaded neither by PIL or OpenCV lib.

Since the author did not provide the HASH checksum of the archive file "DocBank_500K_ori_img.zip" and it's really large, I'd rather not to re-download it to check the completeness of my downloaded file.

**Comment by liminghao1630** [comment]
It is recommended that you check the integrity of the picture when reading in, or use try-catch to catch errors and skip invalid pictures.

**Comment by tankgit** [comment]
fine
