### ISSUE TITLE
Error when downloading dataset

### ISSUE THREAD

**Issue by youngbin-ro** [doc-analysis/DocBank#45]
I tried to download the dataset in the [dataset homepage](https://doc-analysis.github.io/docbank-page/index.html).
But, following error occurred when I clicked the each dataset link.

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:f11eb78c-a01e-000e-3bae-9dc1e2000000 Time:2023-06-13T04:19:31.5518598Z</Message>
</Error>
```

Is there any other way to download the dataset?

**Comment by wolfshow** [comment]
adding the string "?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D" to the end of the current URL will be ok.

**Comment by youngbin-ro** [comment]
@wolfshow 
It works 👍  Thank you!
