### ISSUE TITLE
Public access is not permitted on this storage account

### ISSUE THREAD

**Issue by MIracleyin** [doc-analysis/DocBank#47]
Hey, I can't download DocBank anymore.

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>
Public access is not permitted on this storage account. RequestId:b7c5e5e6-301e-0041-21a3-b0b0b6000000 Time:2023-07-07T07:21:41.1497126Z
</Message>
</Error>
"""

**Comment by liminghao1630** [comment]
The download link is fixed. Thanks for using our dataset.

**Comment by MIracleyin** [comment]
Thanks for your help. 
But the download link works fine in Chrome, but those can't work for the 'wget' tool.

**Comment by MIracleyin** [comment]
https://stackoverflow.com/questions/36927341/download-azure-blob-with-shared-access-signature-using-wget-or-curl
wget "copy_download_url"
wget need '""' to download Azure blob files. Thanks for your help again.
