### ISSUE TITLE
Request 403 for Dataset resource

### ISSUE THREAD

**Issue by plommon** [doc-analysis/DocBank#49]
Hi guys, I got 403 response from dataset URL with following message: 

```xml
<Error>
    <Code>AuthenticationFailed</Code>
    <Message>
        Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:63fa7064-c01e-0055-782d-92f8d9000000 Time:2024-04-19T07:46:53.2863477Z
    </Message>
    <AuthenticationErrorDetail>
        Signature did not match. String to sign used was layoutlm r b o 2023-06-08T08:48:15Z 2033-06-08T16:48:15Z https 2022-11-02
    </AuthenticationErrorDetail>
</Error>
```

**Comment by mjun0812** [comment]
Signature key appears to have expired.

@wolfshow @liminghao1630
Please upgrade the signature key for the dataset.

**Comment by ppaanngggg** [comment]
https://hyper.ai/datasets/21605  try this?

**Comment by ppaanngggg** [comment]
> > https://hyper.ai/datasets/21605 try this?
> 
> Also not available?

yes, no seed at all

**Comment by mjun0812** [comment]
According to the readme of this repository, secondary distribution of the dataset is prohibited.
 Hopefully the distributor will address this or aprove it to a more easily hostable Huggingface or similar.

**Comment by JulioZhao97** [comment]
> > > https://hyper.ai/datasets/21605 try this?
> > 
> > 
> > Also not available?
> 
> yes, no seed at all

You can download from OpenDataLab, here is the link: https://opendatalab.com/OpenDataLab/DocBank

**Comment by ppaanngggg** [comment]
> > > > https://hyper.ai/datasets/21605 try this?
> > > 
> > > 
> > > Also not available?
> > 
> > 
> > yes, no seed at all
> 
> You can download from OpenDataLab, here is the link: https://opendatalab.com/OpenDataLab/DocBank

You are the real hero

**Comment by ppaanngggg** [comment]
> According to the readme of this repository, secondary distribution of the dataset is prohibited. Hopefully the distributor will address this or aprove it to a more easily hostable Huggingface or similar.

Yes, official huggingface repo is the best.

**Comment by JulioZhao97** [comment]
> > > > > https://hyper.ai/datasets/21605 try this?
> > > > 
> > > > 
> > > > Also not available?
> > > 
> > > 
> > > yes, no seed at all
> > 
> > 
> > You can download from OpenDataLab, here is the link: https://opendatalab.com/OpenDataLab/DocBank
> 
> You are the real hero

LOL. Don't thank me, thank OpenDataLab!

**Comment by FrancescoSaverioZuppichini** [comment]
same here, lol

**Comment by Koruvika** [comment]
I have downloaded the data using aria2c, but I can't unzip it, has anyone encountered the same problem? :(

**Comment by liminghao1630** [comment]
Hi, we have uploaded the datasets on HuggingFace, please get the datasets from the following link:
https://huggingface.co/datasets/liminghao1630/DocBank
https://huggingface.co/datasets/liminghao1630/TableBank

**Comment by mjun0812** [comment]
> Hi, we have uploaded the datasets on HuggingFace, please get the datasets from the following link: https://huggingface.co/datasets/liminghao1630/DocBank https://huggingface.co/datasets/liminghao1630/TableBank

Great work! Thank you!
