### ISSUE TITLE
模型怎么用

### ISSUE THREAD

**Issue by Bourne-M** [doc-analysis/DocBank#6]
请问模型怎么使用呢？layoutlm的run_seq_labeling是不是不能用于这个数据集呀？

**Comment by liminghao1630** [comment]
可以，需要自行修改dataset类

**Comment by Bourne-M** [comment]
> 可以，需要自行修改dataset类

您是作者啊！活捉
请问能否提供下您的代码呢？我改了下，没有跑起来，谢谢

**Comment by cococedric14** [comment]
@Bourne-M did you use the model successfully? If so, can you share the modified class?
