### ISSUE TITLE
How can I infer?

### ISSUE THREAD

**Issue by gabrielcustodio** [doc-analysis/DocBank#8]
Do I need retrain to infer? Or can I use pre trained model and infer on Document Image Classification?
Should I use LayoutML to use the pre-trained model and infer?
Why didn't I find a script to infer, but one to retrain.

**Comment by liminghao1630** [comment]
We provide trained models, please refer to LayoutLM fo inference script.

**Comment by NeverInAsh** [comment]
can you link to the script you are talking about.
